spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/retrospect
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
